/**
 * src/batch/resolved_writer.cpp
 * ===============================
 * WO-VSIM-62C — run.vsim.resolved Writer Implementation
 *
 * Serialises a VsimDocument into canonical VSIM format, prefixed by a
 * run-identification header comment block (spec §4).
 *
 * WO-VSIM-62C | beta-12
 */

#include "include/batch/resolved_writer.hpp"

#include <fstream>
#include <sstream>
#include <stdexcept>

namespace vsim {
namespace batch {

// ── helpers ───────────────────────────────────────────────────────────────────

static void w_str  (std::ostream& o, const std::string& k, const std::string& v)
	{ o << k << " = \"" << v << "\"\n"; }
static void w_dbl  (std::ostream& o, const std::string& k, double v)
	{ o << k << " = " << v << "\n"; }
static void w_int  (std::ostream& o, const std::string& k, int v)
	{ o << k << " = " << v << "\n"; }
static void w_bool (std::ostream& o, const std::string& k, bool v)
	{ o << k << " = " << (v ? "true" : "false") << "\n"; }
static void w_u64  (std::ostream& o, const std::string& k, uint64_t v)
	{ o << k << " = " << v << "\n"; }

// ── ResolvedWriter::write ─────────────────────────────────────────────────────

void ResolvedWriter::write(const VsimDocument& doc,
							const BatchRunSpec&  spec,
							const std::string&   study_name,
							const std::string&   output_path)
{
	std::ofstream f(output_path);
	if (!f.is_open())
		throw std::runtime_error("ResolvedWriter: cannot write " + output_path);

	// ── header comment block ──────────────────────────────────────────────
	f << "# run.vsim.resolved\n";
	f << "# Generated by VSEPR-SIM batch runner\n";
	f << "# study:     " << study_name  << "\n";
	f << "# run_id:    " << spec.run_id  << "\n";
	f << "# replicate: " << spec.replicate << "\n";
	f << "# axes:      ";
	{
		bool first = true;
		for (const auto& [k, v] : spec.axis_values) {
			if (!first) f << ", "; first = false;
			f << k << "=" << v;
		}
	}
	f << "\n";
	f << "# seeds:     foundation=" << spec.seed_foundation
	  << " defect="    << spec.seed_defect
	  << " formation=" << spec.seed_formation
	  << " thermal="   << spec.seed_thermal
	  << " placement=" << spec.seed_placement << "\n\n";

	// ── [project] ─────────────────────────────────────────────────────────
	f << "[project]\n";
	w_str(f, "name",    doc.project.name);
	if (!doc.project.version.empty())     w_str(f, "version", doc.project.version);
	if (doc.project.seed_base)            w_u64(f, "seed_base", doc.project.seed_base);
	f << "\n";

	// ── [material] ───────────────────────────────────────────────────────
	if (!doc.material.formula.empty()) {
		f << "[material]\n";
		w_str(f, "formula", doc.material.formula);
		if (!doc.material.prototype.empty())   w_str(f, "prototype",   doc.material.prototype);
		if (!doc.material.structure.empty())   w_str(f, "structure",   doc.material.structure);
		if (!doc.material.space_group.empty()) w_str(f, "space_group", doc.material.space_group);
		if (!doc.material.lattice.empty())     w_str(f, "lattice",     doc.material.lattice);
		if (!doc.material.phase.empty())       w_str(f, "phase",       doc.material.phase);
		f << "\n";
	}

	// ── [environment] ────────────────────────────────────────────────────
	{
		f << "[environment]\n";
		w_dbl(f, "temperature", doc.environment.temperature);
		w_dbl(f, "pressure",    doc.environment.pressure);
		if (!doc.environment.medium.empty()) w_str(f, "medium", doc.environment.medium);
		f << "\n";
	}

	// ── [run] ─────────────────────────────────────────────────────────────
	{
		f << "[run]\n";
		w_int(f, "max_steps", doc.run.max_steps);
		w_dbl(f, "dt_fs",     doc.run.dt_fs);
		if (!doc.run.mode.empty())         w_str(f, "mode",         doc.run.mode);
		if (!doc.run.output_level.empty()) w_str(f, "output_level", doc.run.output_level);
		f << "\n";
	}

	// ── [simulation] ─────────────────────────────────────────────────────
	{
		f << "[simulation]\n";
		w_int (f, "fire_max_steps", doc.simulation.fire_max_steps);
		w_dbl (f, "fire_dt_fs",     doc.simulation.fire_dt_fs);
		w_dbl (f, "box_size_ang",   doc.simulation.box_size_ang);
		w_bool(f, "periodic",        doc.simulation.periodic);
		if (doc.simulation.use_ewald) {
			w_bool(f, "use_ewald",   doc.simulation.use_ewald);
			w_dbl (f, "ewald_alpha", doc.simulation.ewald_alpha);
			w_dbl (f, "ewald_rcut",  doc.simulation.ewald_rcut);
			w_int (f, "ewald_kmax",  doc.simulation.ewald_kmax);
		}
		f << "\n";
	}

	// ── [cell] ────────────────────────────────────────────────────────────
	if (doc.cell.has_cell()) {
		f << "[cell]\n";
		w_str(f, "type", doc.cell.type);
		w_dbl(f, "lx",   doc.cell.lx);
		w_dbl(f, "ly",   doc.cell.ly);
		w_dbl(f, "lz",   doc.cell.lz);
		if (!doc.cell.units.empty()) w_str(f, "units", doc.cell.units);
		f << "\n";
	}

	// ── [pbc] ─────────────────────────────────────────────────────────────
	if (doc.pbc.minimum_image || doc.simulation.periodic) {
		f << "[pbc]\n";
		w_bool(f, "minimum_image",        doc.pbc.minimum_image);
		w_bool(f, "track_images",         doc.pbc.track_images);
		w_bool(f, "unwrap_for_diffusion", doc.pbc.unwrap_for_diffusion);
		f << "\n";
	}

	// ── [verify] (only if declared — ghost thresholds are prohibited) ─────
	{
		const auto& v = doc.pipeline_verify;
		if (v.enabled) {
			f << "[verify]\n";
			w_bool(f, "enabled",            v.enabled);
			w_bool(f, "write_verify_report", v.write_verify_report);
			if (v.structure.enabled) {
				f << "\n[verify.structure]\n";
				w_bool(f, "enabled", v.structure.enabled);
				if (!v.structure.expected_prototype.empty())
					w_str(f, "expected_prototype", v.structure.expected_prototype);
				if (v.structure.expected_coordination >= 0)
					w_int(f, "expected_coordination", v.structure.expected_coordination);
				if (v.structure.nearest_neighbor_tolerance_A > 0.0)
					w_dbl(f, "nearest_neighbor_tolerance_A", v.structure.nearest_neighbor_tolerance_A);
			}
			if (v.msd.enabled) {
				f << "\n[verify.msd]\n";
				w_bool(f, "enabled",           v.msd.enabled);
				w_bool(f, "expect_bounded_solid", v.msd.expect_bounded_solid);
				if (v.msd.max_msd_A2 > 0.0) w_dbl(f, "max_msd_A2", v.msd.max_msd_A2);
			}
			if (v.mass.enabled) {
				f << "\n[verify.mass]\n";
				w_bool(f, "enabled",             v.mass.enabled);
				w_dbl(f, "relative_tolerance",   v.mass.relative_tolerance);
			}
			f << "\n";
		}
	}

	// ── [export] ─────────────────────────────────────────────────────────
	if (doc.exports.write_xyz || doc.exports.write_analysis_json) {
		f << "[export]\n";
		if (doc.exports.write_xyz)           w_bool(f, "write_xyz",           doc.exports.write_xyz);
		if (doc.exports.write_analysis_json) w_bool(f, "write_analysis_json", doc.exports.write_analysis_json);
		if (doc.exports.write_metrics_tsv)   w_bool(f, "write_metrics_tsv",   doc.exports.write_metrics_tsv);
		if (!doc.exports.output_dir.empty()) w_str (f, "output_dir",          doc.exports.output_dir);
		f << "\n";
	}
}

} // namespace batch
} // namespace vsim
