#pragma once
/**
 * needle_ring_generator.hpp
 *
 * Electrohydrodynamic Simulation — Stage 1: CAD / Geometry
 *
 * Configuration (b): Needle-ring electrode for ion injection.
 * A sharp needle tip (cathode or anode) faces a ring electrode across a gap.
 * Corona discharge at the needle tip injects ions that are accelerated by
 * the electric field, dragging bulk fluid and producing unidirectional flow
 * through the ring aperture.
 *
 * Geometry:
 *   - Needle with tip radius r_tip, oriented along +z
 *   - Ring electrode of inner radius R_ring in a plane at z = d_gap
 *   - Flow passes through the ring aperture in the +z direction
 *
 * The dominant pumping mechanism is Coulomb / ion-drag: f = ρ_e · E,
 * where ρ_e is the injected space-charge density from corona.
 */

#include "sim/ehd/ehd_types.hpp"
#include <vector>
#include <cmath>

namespace vsepr {
namespace ehd {
namespace cad {

// ============================================================================
// Needle-Ring Parameters
// ============================================================================

struct NeedleRingParams {
    double tip_radius     = 50.0e-6;   // r_tip (m) — needle tip curvature
    double ring_radius    = 2.0e-3;    // R_ring (m) — ring inner radius
    double gap            = 5.0e-3;    // d_gap (m) — needle tip to ring plane
    double needle_length  = 10.0e-3;   // total needle shaft length (m)
    double ring_thickness = 0.5e-3;    // ring cross-section thickness (m)
    int    ring_pts       = 72;        // angular resolution for ring
    int    needle_pts     = 50;        // axial resolution for needle profile
};

inline NeedleRingParams from_ehd_needle_ring(const EHDParameters& p) {
    NeedleRingParams nr;
    nr.tip_radius  = p.needle_tip_radius_m;
    nr.ring_radius = p.ring_inner_radius_m;
    nr.gap         = p.needle_ring_gap_m;
    return nr;
}

// ============================================================================
// Needle Profile Point (axisymmetric)
// ============================================================================

struct NeedleProfilePoint {
    double z;      // axial position (m) — tip at z = 0
    double radius; // local needle radius at this z (m)
};

/**
 * Generate the needle profile as an axisymmetric taper ending in a
 * hyperboloidal tip.
 *
 * Profile: r(z) = r_tip · cosh(z / r_tip)  for z near tip,
 *          linearly expanding to shaft radius further back.
 *
 * The tip is at z = 0; the ring is at z = d_gap.
 */
inline std::vector<NeedleProfilePoint> generate_needle_profile(
    const NeedleRingParams& nr)
{
    std::vector<NeedleProfilePoint> profile;
    profile.reserve(static_cast<size_t>(nr.needle_pts + 1));

    double shaft_radius = nr.tip_radius * 20.0;  // shaft is ~20× tip
    double dz = nr.needle_length / nr.needle_pts;

    for (int i = 0; i <= nr.needle_pts; ++i) {
        double z = -nr.needle_length + i * dz;  // z < 0 is behind tip, z=0 is tip
        double r;
        if (z >= -nr.tip_radius * 5.0) {
            // Hyperboloidal region near tip
            r = nr.tip_radius * std::cosh(z / nr.tip_radius);
            r = std::min(r, shaft_radius);
        } else {
            // Shaft region — constant radius
            r = shaft_radius;
        }
        profile.push_back({z, r});
    }
    return profile;
}

/**
 * Generate the ring electrode as a circle of points at z = d_gap.
 */
inline std::vector<Vec3> generate_ring_electrode(const NeedleRingParams& nr) {
    std::vector<Vec3> ring;
    ring.reserve(static_cast<size_t>(nr.ring_pts));

    for (int i = 0; i < nr.ring_pts; ++i) {
        double theta = 2.0 * constants::PI * i / nr.ring_pts;
        ring.emplace_back(
            nr.ring_radius * std::cos(theta),
            nr.ring_radius * std::sin(theta),
            nr.gap);
    }
    return ring;
}

/**
 * Approximate electric field at the needle tip (hyperboloidal approximation):
 *   E_tip ≈ ΔV / (r_tip · ln(2·d_gap / r_tip))
 *
 * This is the field enhancement factor that determines corona onset.
 */
inline double needle_tip_field(double delta_V, double r_tip, double d_gap) {
    if (r_tip <= 0.0 || d_gap <= 0.0) return 0.0;
    return delta_V / (r_tip * std::log(2.0 * d_gap / r_tip));
}

/**
 * Peek's empirical corona onset field in air (V/m):
 *   E_onset = 3.1e6 · δ · (1 + 0.308 / √(δ·r_tip))
 *
 * where δ = relative air density (≈1.0 at STP), r_tip in metres.
 */
inline double peek_onset_field(double r_tip, double delta_air = 1.0) {
    if (r_tip <= 0.0) return 0.0;
    return 3.1e6 * delta_air
         * (1.0 + 0.308 / std::sqrt(delta_air * r_tip));
}

/**
 * Ion-drag pressure generated by needle-ring injection:
 *   ΔP_ion ≈ (I · d_gap) / (μ_i · A_ring)
 *
 * where I is the corona current, μ_i is the ion mobility, and
 * A_ring is the ring aperture area.
 */
inline double ion_drag_pressure(double corona_current,
                                 double d_gap,
                                 double mu_ion,
                                 double ring_radius)
{
    double A = constants::PI * ring_radius * ring_radius;
    if (mu_ion <= 0.0 || A <= 0.0) return 0.0;
    return corona_current * d_gap / (mu_ion * A);
}

} // namespace cad
} // namespace ehd
} // namespace vsepr
