#pragma once
/**
 * step_export.hpp
 *
 * Electrohydrodynamic Simulation — Stage 1: CAD / Geometry
 *
 * STEP-style geometry export for EHD device assemblies.
 * Writes a structured text manifest of named bodies and surfaces that can be
 * consumed by external meshing / solver tools (ANSYS, OpenFOAM, gmsh, etc.).
 *
 * The manifest includes:
 *   - body name, type, material role
 *   - bounding geometry parameters
 *   - surface tags for boundary-condition mapping
 *
 * For true STEP (ISO 10303) binary export, this manifest is the precursor;
 * the actual B-rep kernel integration is a future extension point.
 */

#include "sim/ehd/cad/electrode_layout.hpp"
#include "sim/ehd/cad/tube_body_generator.hpp"
#include "sim/ehd/cad/helix_generator.hpp"
#include <fstream>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>

namespace vsepr {
namespace ehd {
namespace cad {

// ============================================================================
// Named Body Entry (STEP manifest)
// ============================================================================

struct NamedBody {
    std::string name;           // "fluid_domain", "electrode_pos", "tube_wall", etc.
    std::string role;           // "fluid", "conductor", "dielectric", "inlet", "outlet"
    std::string geometry_type;  // "cylinder", "helix_sweep", "annulus", "cap"
    std::string notes;

    // Bounding parameters (for manifest readability)
    double z_min = 0.0, z_max = 0.0;
    double r_inner = 0.0, r_outer = 0.0;
};

// ============================================================================
// STEP Manifest Writer
// ============================================================================

struct StepManifest {
    std::string case_id;
    std::vector<NamedBody> bodies;

    void add_body(const NamedBody& b) { bodies.push_back(b); }

    /**
     * Build a complete manifest from EHD parameters and electrode layout.
     */
    static StepManifest build(const EHDParameters& p,
                              const ElectrodeLayout& layout,
                              const std::string& id = "EHD-001")
    {
        StepManifest m;
        m.case_id = id;

        double total_L = p.inlet_length_m + p.tube_length_m + p.outlet_length_m;

        // Fluid domain
        m.add_body({"fluid_domain", "fluid", "cylinder",
                     "Interior fluid volume (helix subtracted at meshing stage)",
                     0.0, total_L, 0.0, p.tube_radius_m});

        // Tube wall
        m.add_body({"tube_wall", "dielectric", "annulus",
                     "Outer tube wall solid",
                     0.0, total_L, p.tube_radius_m, p.tube_radius_m + 0.5e-3});

        // Electrodes
        for (const auto& e : layout.electrodes) {
            std::string role = (e.polarity == Polarity::GROUNDED) ? "conductor_gnd" : "conductor";
            std::string gtype = (e.type == ElectrodeType::HELICAL) ? "helix_sweep" : "cylinder";
            m.add_body({e.name, role, gtype,
                        "Voltage = " + std::to_string(e.voltage) + " V",
                        e.z_start, e.z_start + e.length,
                        0.0, e.radius});
        }

        // Inlet / outlet caps
        m.add_body({"inlet", "boundary", "cap", "Flow inlet face",
                     0.0, 0.0, 0.0, p.tube_radius_m});
        m.add_body({"outlet", "boundary", "cap", "Flow outlet face",
                     total_L, total_L, 0.0, p.tube_radius_m});

        // Core support (central rod if present)
        if (p.wall_clearance_m > 0.0) {
            m.add_body({"core_support", "dielectric", "cylinder",
                        "Central support rod (if applicable)",
                        p.inlet_length_m,
                        p.inlet_length_m + p.tube_length_m,
                        0.0, p.wall_clearance_m});
        }

        return m;
    }

    /**
     * Write the manifest to a text file.
     */
    bool write(const std::string& filepath) const {
        std::ofstream out(filepath);
        if (!out.is_open()) return false;

        out << "# ============================================================================\n";
        out << "# EHD STEP Manifest — Case: " << case_id << "\n";
        out << "# ============================================================================\n";
        out << "# Named bodies and surface tags for meshing / solver import.\n";
        out << "# Generated by vsepr::ehd::cad::StepManifest\n";
        out << "# ============================================================================\n\n";

        out << std::fixed << std::setprecision(6);

        for (size_t i = 0; i < bodies.size(); ++i) {
            const auto& b = bodies[i];
            out << "[body." << i << "]\n";
            out << "  name          = " << b.name << "\n";
            out << "  role          = " << b.role << "\n";
            out << "  geometry_type = " << b.geometry_type << "\n";
            out << "  z_min         = " << b.z_min << "\n";
            out << "  z_max         = " << b.z_max << "\n";
            out << "  r_inner       = " << b.r_inner << "\n";
            out << "  r_outer       = " << b.r_outer << "\n";
            out << "  notes         = " << b.notes << "\n\n";
        }

        return true;
    }
};

} // namespace cad
} // namespace ehd
} // namespace vsepr
