#!/usr/bin/env bash
################################################################################
# VSEPR-Sim Reporting System Installer (Deterministic)
# Version: 2.3.1 FINAL
################################################################################

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="$ROOT/.venv"

echo "[*] VSEPR-Sim Reporting System Installer"
echo "[*] Repository root: $ROOT"
echo ""

# --- System dependencies (Debian/Ubuntu/WSL) ---
if command -v apt-get >/dev/null 2>&1; then
    echo "[*] Detected apt-get - installing system dependencies..."
    
    sudo apt-get update
    sudo apt-get install -y \
        python3 \
        python3-venv \
        python3-pip \
        pandoc \
        texlive-latex-recommended \
        texlive-latex-extra \
        texlive-fonts-recommended \
        latexmk \
        graphviz
    
    echo "[✓] System dependencies installed"
    
elif command -v dnf >/dev/null 2>&1; then
    echo "[*] Detected dnf - installing system dependencies..."
    
    sudo dnf install -y \
        python3 \
        python3-pip \
        pandoc \
        texlive \
        texlive-latex \
        latexmk \
        graphviz
    
    echo "[✓] System dependencies installed"
    
else
    echo "[!] Package manager not found (apt-get or dnf)"
    echo "[!] Please install manually:"
    echo "    - Python 3 + pip + venv"
    echo "    - pandoc"
    echo "    - LaTeX (texlive)"
    echo "    - latexmk"
    echo "    - graphviz"
    exit 1
fi

# --- Python virtual environment ---
echo ""
echo "[*] Creating Python virtual environment..."

if [[ -d "$VENV" ]]; then
    echo "[!] Virtual environment already exists: $VENV"
    echo "[!] Removing old environment..."
    rm -rf "$VENV"
fi

python3 -m venv "$VENV"

# shellcheck disable=SC1091
source "$VENV/bin/activate"

echo "[✓] Virtual environment created: $VENV"

# --- Upgrade pip ---
echo ""
echo "[*] Upgrading pip..."
python -m pip install --upgrade pip wheel setuptools

# --- Install Python packages ---
echo ""
echo "[*] Installing Python packages..."

python -m pip install \
    jupyterlab \
    notebook \
    numpy \
    pandas \
    matplotlib \
    seaborn \
    plotly \
    scipy \
    rdkit-pypi \
    py3Dmol \
    nglview \
    markdown \
    nbconvert \
    ipywidgets

echo "[✓] Python packages installed"

# --- Create requirements.txt ---
echo ""
echo "[*] Creating requirements.txt..."

cat > "$ROOT/requirements.txt" << 'EOF'
# VSEPR-Sim Reporting Requirements
# Generated by install_reporting.sh

# Core Jupyter
jupyterlab>=3.0.0
notebook>=6.4.0

# Data Science
numpy>=1.21.0
pandas>=1.3.0
matplotlib>=3.4.0
seaborn>=0.11.0
plotly>=5.0.0
scipy>=1.7.0

# Molecular Chemistry
rdkit-pypi>=2022.3.1
py3Dmol>=1.8.0
nglview>=3.0.0

# Document Generation
markdown>=3.3.0
nbconvert>=6.1.0
ipywidgets>=7.6.0
EOF

echo "[✓] Requirements saved: $ROOT/requirements.txt"

# --- Create activation helper ---
echo ""
echo "[*] Creating activation helper..."

cat > "$ROOT/activate_env.sh" << 'EOF'
#!/usr/bin/env bash
# Activate VSEPR-Sim reporting environment

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$ROOT/.venv"

if [[ ! -d "$VENV" ]]; then
    echo "[!] Virtual environment not found: $VENV"
    echo "[!] Run: ./scripts/install_reporting.sh"
    exit 1
fi

# shellcheck disable=SC1091
source "$VENV/bin/activate"

echo "[✓] VSEPR-Sim reporting environment activated"
echo ""
echo "Available commands:"
echo "  jupyter lab           # Start Jupyter Lab"
echo "  jupyter notebook      # Start Jupyter Notebook"
echo "  python                # Python with all packages"
echo "  ./scripts/run_report.sh  # Generate all reports"
EOF

chmod +x "$ROOT/activate_env.sh"

echo "[✓] Activation helper created: $ROOT/activate_env.sh"

# --- Final summary ---
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║  ✅ Reporting System Installation Complete!                   ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. Activate environment:"
echo "     source activate_env.sh"
echo ""
echo "  2. Generate reports:"
echo "     ./scripts/run_report.sh"
echo ""
echo "  3. Start Jupyter:"
echo "     source activate_env.sh && jupyter lab"
echo ""
