/**
 * deep_verification.cpp
 * ---------------------
 * Automated continuous deep verification suite.
 *
 * Static suites (empirical database):
 *   A. LJ parameter audit (42 UFF elements vs Rappe 1992)
 *   B. Homonuclear dimer sweeps (energy curves, r_min, smoothness)
 *   C. Heteronuclear ion pair Coulomb + force consistency
 *   D. Crystal geometry vs Wyckoff (30 structures)
 *   E. Molecule bond detection (9 molecules)
 *   F. Composite force-energy consistency (H2O, NH3, CH4, Ar2)
 *   G. Noble gas cluster FIRE — two-layer: descent + convergence quality
 *   H. Full solvent dielectric sweep (19 CRC_104 solvents)
 *   N. Restoring-force scan: homonuclear dimers He2--Xe2 (compression+extension)
 *   Q. Relaxed crystal stability: 2x2x2 supercell FIRE + nn/overlap guard
 *
 * Randomized suites (different result each run, seed logged):
 *   I. Random atom-pair LJ force-energy consistency (N_RAND=100)
 *   J. Random Coulomb law 1/r verification (N_RAND=80)
 *   K. Random dielectric ratio check (N_RAND=60)
 *   L. Random crystal supercell atom-count verification
 *   M. NVE energy conservation on random Ar clusters
 *
 * Downloaded refs suite:
 *   P. Verify bond lengths against PubChem/NIST downloaded_refs.hpp
 *      (skipped if verification/downloaded_refs.hpp not present)
 *
 * Usage:
 *   ./deep_verification [--verbose] [--seed N] [--rand-iters N]
 *   Exit code 0 = all pass, 1 = failures present
 *   Writes verification/deep/report.txt and status.txt
 */

#include "atomistic/core/state.hpp"
#include "atomistic/core/environment.hpp"
#include "atomistic/core/empirical_reference.hpp"
#include "atomistic/models/model.hpp"
#include "atomistic/models/composite.hpp"
#include "atomistic/integrators/fire.hpp"
#include "atomistic/parsers/xyz_parser.hpp"
#include "atomistic/crystal/unit_cell.hpp"
#include "atomistic/crystal/supercell.hpp"
#include "io/xyz_format.hpp"
#include <cmath>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <random>
#include <algorithm>
#include <vector>
#include <string>
#include <sys/stat.h>

// Downloaded refs (PubChem + AFLOW) -- optional, generated by fetch_empirical.py
#if __has_include("downloaded_refs.hpp")
#  include "downloaded_refs.hpp"
#  define HAS_DOWNLOADED_REFS 1
#else
#  define HAS_DOWNLOADED_REFS 0
#endif

using namespace atomistic;
using namespace atomistic::crystal;
using namespace empirical;

// ============================================================================
// Infrastructure
// ============================================================================

static int  g_pass = 0, g_fail = 0, g_skip = 0;
static bool g_verbose = false;
static std::ostringstream g_report;

// Random infrastructure -- seeded once in main(), used by suites I-M
static uint64_t g_seed = 0;
static std::mt19937_64 g_rng;
static int g_rand_iters = 100; // default random iterations per suite

inline double rnd_uniform(double lo, double hi) {
    std::uniform_real_distribution<double> d(lo, hi);
    return d(g_rng);
}
inline int rnd_int(int lo, int hi_inclusive) {
    std::uniform_int_distribution<int> d(lo, hi_inclusive);
    return d(g_rng);
}

static void mkdir_p(const std::string& path) {
    std::string cmd = "mkdir -p \"" + path + "\"";
    system(cmd.c_str());
}

static void check(bool ok, const std::string& name, const std::string& detail = "")
{
    if (ok) {
        ++g_pass;
        if (g_verbose) std::printf("  [PASS]  %s  %s\n", name.c_str(), detail.c_str());
    } else {
        ++g_fail;
        std::printf("  [FAIL]  %s  %s\n", name.c_str(), detail.c_str());
    }
    g_report << (ok ? "[PASS] " : "[FAIL] ") << name;
    if (!detail.empty()) g_report << "  (" << detail << ")";
    g_report << "\n";
}

static void skip(const std::string& name, const std::string& reason)
{
    ++g_skip;
    if (g_verbose) std::printf("  [SKIP]  %s  (%s)\n", name.c_str(), reason.c_str());
    g_report << "[SKIP] " << name << "  (" << reason << ")\n";
}

static State parse(const vsepr::io::XYZMolecule& mol)
{
    State s = parsers::from_xyz(mol);
    s.F.resize(s.N, {0,0,0});
    return s;
}

static double mic_dist(const Vec3& a, const Vec3& b, const BoxPBC& box) {
    Vec3 d = box.enabled ? box.delta(a, b) : Vec3{a.x-b.x, a.y-b.y, a.z-b.z};
    return std::sqrt(d.x*d.x + d.y*d.y + d.z*d.z);
}

static double nn_dist(const State& s) {
    double dmin = 1e30;
    for (uint32_t i = 0; i < s.N; ++i)
        for (uint32_t j = i+1; j < s.N; ++j) {
            double d = mic_dist(s.X[i], s.X[j], s.box);
            if (d < dmin) dmin = d;
        }
    return dmin;
}

// ============================================================================
// A. LJ Parameter Audit
// ============================================================================

static void suite_A(IModel& model, const ModelParams& mp)
{
    g_report << "\n[Suite A] LJ Parameter Audit\n";
    std::printf("\n--- Suite A: LJ Parameter Audit (%d elements) ---\n", N_LJ_REFS);

    for (int i = 0; i < N_LJ_REFS; ++i) {
        const auto& ref = LJ_REFS[i];

        // Create homonuclear dimer at r_min, evaluate energy
        vsepr::io::XYZMolecule m;
        m.atoms.emplace_back(ref.symbol, 0.0, 0.0, 0.0);
        m.atoms.emplace_back(ref.symbol, ref.r_min, 0.0, 0.0);
        State s = parse(m);
        model.eval(s, mp);

        // At r_min: U = -epsilon (for homonuclear)
        double U_expect = -ref.epsilon;
        double err = std::abs(s.E.UvdW - U_expect);
        std::string tag = std::string(ref.symbol) + " dimer at r_min";

        check(err < 0.001, tag,
              "U=" + std::to_string(s.E.UvdW).substr(0,8) +
              " expect=" + std::to_string(U_expect).substr(0,8));
    }
}

// ============================================================================
// B. Homonuclear Dimer Sweeps
// ============================================================================

static void suite_B(IModel& model, const ModelParams& mp)
{
    g_report << "\n[Suite B] Homonuclear Dimer Sweeps\n";
    std::printf("\n--- Suite B: Homonuclear Dimer Sweeps ---\n");

    const char* elements[] = {"H", "C", "N", "O", "Ar", "Fe", "Cu", "Na", "Cl", "Si"};
    int n_elem = sizeof(elements) / sizeof(elements[0]);

    for (int e = 0; e < n_elem; ++e) {
        const char* sym = elements[e];
        auto lj = find_lj(0);  // need Z
        // Look up by symbol
        for (int i = 0; i < N_LJ_REFS; ++i) {
            if (std::string(LJ_REFS[i].symbol) == sym) {
                lj = LJ_REFS[i];
                break;
            }
        }
        if (!lj) { skip(std::string(sym) + " sweep", "no LJ params"); continue; }

        // Sweep from 0.8*sigma to 3*sigma
        double sigma = lj->sigma;
        bool finite_ok = true, minimum_found = false;
        double r_min_found = 0, U_min_found = 1e30;
        double prev_U = 1e30;
        bool smooth = true;

        for (double r = 0.8*sigma; r <= 3.0*sigma; r += 0.02*sigma) {
            vsepr::io::XYZMolecule m;
            m.atoms.emplace_back(sym, 0.0, 0.0, 0.0);
            m.atoms.emplace_back(sym, r, 0.0, 0.0);
            State s = parse(m);
            model.eval(s, mp);
            double U = s.E.UvdW;
            if (!std::isfinite(U)) { finite_ok = false; break; }
            if (U < U_min_found) { U_min_found = U; r_min_found = r; }
            // Smoothness: energy change per step should be monotonic in each
            // region (repulsive or attractive). Large non-monotonic jumps
            // indicate numerical issues. Allow large changes in repulsive wall.
            if (prev_U < 1e29 && r > sigma) {
                // Only check smoothness past sigma (attractive region)
                if (std::abs(U - prev_U) > 5.0 * lj->epsilon)
                    smooth = false;
            }
            prev_U = U;
        }

        if (U_min_found < 0) minimum_found = true;
        std::string tag = std::string(sym) + " sweep";
        check(finite_ok, tag + ": all finite");
        check(minimum_found, tag + ": bound state found");
        check(smooth, tag + ": smooth (steps < 5*eps)");
        check(std::abs(r_min_found - lj->r_min) < 0.1,
              tag + ": r_min within 0.1A",
              "found=" + std::to_string(r_min_found).substr(0,5) +
              " UFF=" + std::to_string(lj->r_min).substr(0,5));
    }
}

// ============================================================================
// C. Heteronuclear Ion Pair Coulomb
// ============================================================================

static void suite_C(IModel& model, const ModelParams& mp)
{
    g_report << "\n[Suite C] Ion Pair Coulomb Verification\n";
    std::printf("\n--- Suite C: Ion Pair Coulomb ---\n");

    // Test all cation-anion combinations at r=5 A
    struct IonPair { const char* cat; int Z_cat; double q_cat;
                     const char* an;  int Z_an;  double q_an; };
    IonPair pairs[] = {
        {"Na", 11, +1.0, "Cl", 17, -1.0},
        {"Na", 11, +1.0, "F",   9, -1.0},
        {"Cs", 55, +1.0, "Cl", 17, -1.0},
        {"Mg", 12, +2.0, "O",   8, -2.0},
    };

    for (auto& p : pairs) {
        double r = 5.0;
        vsepr::io::XYZMolecule m;
        m.atoms.emplace_back(p.cat, 0.0, 0.0, 0.0);
        m.atoms.emplace_back(p.an, r, 0.0, 0.0);
        State s = parse(m);
        s.Q[0] = p.q_cat; s.Q[1] = p.q_an;
        model.eval(s, mp);

        double U_expect = 332.0636 * p.q_cat * p.q_an / r;
        double err = std::abs(s.E.UCoul - U_expect);
        std::string tag = std::string(p.cat) + "-" + p.an + " Coulomb";

        check(err < 0.1, tag,
              "U=" + std::to_string(s.E.UCoul).substr(0,8) +
              " expect=" + std::to_string(U_expect).substr(0,8));

        // Force-energy check
        double dr = 1e-6;
        vsepr::io::XYZMolecule mp2, mm2;
        mp2.atoms.emplace_back(p.cat, dr, 0.0, 0.0);
        mp2.atoms.emplace_back(p.an, r, 0.0, 0.0);
        mm2.atoms.emplace_back(p.cat, -dr, 0.0, 0.0);
        mm2.atoms.emplace_back(p.an, r, 0.0, 0.0);
        State sp = parse(mp2); sp.Q[0] = p.q_cat; sp.Q[1] = p.q_an;
        State sm = parse(mm2); sm.Q[0] = p.q_cat; sm.Q[1] = p.q_an;
        model.eval(sp, mp); model.eval(sm, mp);
        double F_num = -(sp.E.total() - sm.E.total()) / (2.0*dr);
        double F_ana = s.F[0].x;
        double ferr = std::abs(F_num - F_ana);
        check(ferr < 1e-3, tag + " force-energy",
              "err=" + std::to_string(ferr));
    }
}

// ============================================================================
// D. Crystal Geometry Verification
// ============================================================================

static void suite_D()
{
    g_report << "\n[Suite D] Crystal Geometry vs Wyckoff\n";
    std::printf("\n--- Suite D: Crystal Geometry (%d refs) ---\n", N_CRYSTAL_REFS);

    // Map preset name -> factory function
    struct Preset { const char* ref_name; UnitCell (*factory)(); };
    Preset presets[] = {
        {"Al",   presets::aluminum_fcc},
        {"Cu",   presets::copper_fcc},
        {"Au",   presets::gold_fcc},
        {"Fe",   presets::iron_bcc},
        {"NaCl", presets::sodium_chloride},
        {"MgO",  presets::magnesium_oxide},
        {"Si",   presets::silicon_diamond},
        {"CsCl", presets::cesium_chloride},
    };

    for (auto& p : presets) {
        auto ref = find_crystal(p.ref_name);
        if (!ref) { skip(std::string(p.ref_name) + " crystal", "no ref"); continue; }

        UnitCell uc = p.factory();
        auto sc = construct_supercell(uc, 2, 2, 2);
        State& s = sc.state;
        s.F.resize(s.N, {0,0,0});

        double nn = nn_dist(s);
        uint32_t N_per_cell = uc.num_atoms();

        // Coordination number of first atom
        double cn_cut = ref->nn * 1.15;
        int cn = 0;
        for (uint32_t j = 1; j < s.N; ++j)
            if (mic_dist(s.X[0], s.X[j], s.box) < cn_cut) ++cn;

        std::string tag = std::string(p.ref_name);
        check(std::abs(nn - ref->nn) < ref->tol_a,
              tag + ": nn distance",
              "calc=" + std::to_string(nn).substr(0,5) +
              " ref=" + std::to_string(ref->nn).substr(0,5));
        check(cn == ref->cn,
              tag + ": coordination number",
              "calc=" + std::to_string(cn) + " ref=" + std::to_string(ref->cn));
        check(N_per_cell == (uint32_t)ref->Z_per_cell,
              tag + ": atoms per cell",
              "calc=" + std::to_string(N_per_cell) +
              " ref=" + std::to_string(ref->Z_per_cell));
    }
}

// ============================================================================
// E. Molecule Builder + Bond Detection Coverage
// ============================================================================

static void suite_E()
{
    g_report << "\n[Suite E] Molecule Bond Detection\n";
    std::printf("\n--- Suite E: Molecule Bond Detection ---\n");

    struct MolTest {
        const char* name;
        std::vector<std::pair<const char*, std::array<double,3>>> atoms;
        int expected_bonds;
    };

    // Use approximate geometries; bond detection is distance-based
    MolTest tests[] = {
        {"H2",  {{"H",{0,0,0}}, {"H",{0.74,0,0}}}, 1},
        {"O2",  {{"O",{0,0,0}}, {"O",{1.21,0,0}}}, 1},
        {"N2",  {{"N",{0,0,0}}, {"N",{1.10,0,0}}}, 1},
        {"HF",  {{"H",{0,0,0}}, {"F",{0.92,0,0}}}, 1},
        {"HCl", {{"H",{0,0,0}}, {"Cl",{1.28,0,0}}}, 1},
        {"CO",  {{"C",{0,0,0}}, {"O",{1.13,0,0}}}, 1},
        {"H2O", {{"O",{0,0,0}}, {"H",{0.96,0,0}}, {"H",{-0.24,0.93,0}}}, 2},
        {"NH3", {{"N",{0,0,0}}, {"H",{0.94,0.27,0}}, {"H",{-0.47,0.82,0}}, {"H",{-0.47,-0.27,0.82}}}, 3},
        {"CH4", {{"C",{0,0,0}}, {"H",{0.63,0.63,0.63}}, {"H",{0.63,-0.63,-0.63}},
                 {"H",{-0.63,0.63,-0.63}}, {"H",{-0.63,-0.63,0.63}}}, 4},
    };

    for (auto& t : tests) {
        vsepr::io::XYZMolecule m;
        for (auto& [elem, pos] : t.atoms)
            m.atoms.emplace_back(elem, pos[0], pos[1], pos[2]);
        vsepr::io::XYZReader().detect_bonds(m);

        check((int)m.bonds.size() == t.expected_bonds,
              std::string(t.name) + ": bond count",
              "found=" + std::to_string(m.bonds.size()) +
              " expect=" + std::to_string(t.expected_bonds));
    }
}

// ============================================================================
// F. Composite Force-Energy Consistency
// ============================================================================

static void suite_F()
{
    g_report << "\n[Suite F] Composite Force-Energy Consistency\n";
    std::printf("\n--- Suite F: Composite Force-Energy ---\n");

    struct MolGeom {
        const char* name;
        std::vector<std::pair<const char*, std::array<double,3>>> atoms;
    };

    MolGeom mols[] = {
        {"H2O", {{"O",{0,0,0}}, {"H",{0.96,0,0}}, {"H",{-0.24,0.93,0}}}},
        {"NH3", {{"N",{0,0,0}}, {"H",{0.94,0.27,0}}, {"H",{-0.47,0.82,0}}, {"H",{-0.47,-0.27,0.82}}}},
        {"CH4", {{"C",{0,0,0}}, {"H",{0.63,0.63,0.63}}, {"H",{0.63,-0.63,-0.63}},
                 {"H",{-0.63,0.63,-0.63}}, {"H",{-0.63,-0.63,0.63}}}},
        {"Ar2", {{"Ar",{0,0,0}}, {"Ar",{4.0,0,0}}}},
    };

    ModelParams mp; mp.rc = 12.0;
    double dr = 1e-5;

    for (auto& mol : mols) {
        vsepr::io::XYZMolecule m;
        for (auto& [elem, pos] : mol.atoms)
            m.atoms.emplace_back(elem, pos[0], pos[1], pos[2]);
        vsepr::io::XYZReader().detect_bonds(m);
        State s0 = parse(m);
        auto model = create_composite_model(s0);
        model->eval(s0, mp);

        double max_rel = 0;
        bool ok = true;
        for (uint32_t at = 0; at < s0.N; ++at) {
            for (int dim = 0; dim < 3; ++dim) {
                State sp = s0, sm = s0;
                sp.F.assign(sp.N, {0,0,0}); sp.E = {};
                sm.F.assign(sm.N, {0,0,0}); sm.E = {};
                if (dim==0) { sp.X[at].x += dr; sm.X[at].x -= dr; }
                if (dim==1) { sp.X[at].y += dr; sm.X[at].y -= dr; }
                if (dim==2) { sp.X[at].z += dr; sm.X[at].z -= dr; }
                model->eval(sp, mp); model->eval(sm, mp);
                double F_num = -(sp.E.total() - sm.E.total()) / (2.0*dr);
                double F_ana = (dim==0) ? s0.F[at].x
                             : (dim==1) ? s0.F[at].y : s0.F[at].z;
                double scale = std::max(std::abs(F_ana), 1.0);
                double rel = std::abs(F_num - F_ana) / scale;
                if (rel > max_rel) max_rel = rel;
                if (rel > 1e-3) ok = false;
            }
        }
        check(ok, std::string(mol.name) + " composite force-energy",
              "max_rel=" + std::to_string(max_rel));
    }
}

// ============================================================================
// G. Noble Gas Cluster FIRE Relaxation
// ============================================================================

static void suite_G(IModel& model, const ModelParams& mp)
{
    // ---- convergence targets ------------------------------------------------
    // Layer 1  (descent): energy decreased, energy finite (always required)
    // Layer 2 (quality) : Frms < FRMS_TOL, no overlap, dU/atom not stagnating
    //   Frms < 0.10 kcal/mol/A  -- loose threshold adequate for small LJ clusters
    //   nn   > 0.55 * r_min     -- catastrophic overlap / blow-up guard
    //   dU_per_atom < 1e-4      -- energy stagnation guard
    const double FRMS_TOL      = 0.10;
    const double OVERLAP_FRAC  = 0.55;
    const double STAGNATION_EP = 1e-4;

    // Starting geometry: Fibonacci sphere of radius R chosen so nearest-neighbour
    // pairs start at approximately 1.1 * r_min (just inside the attractive well).
    // R = r_min * sqrt(N) / 3.0 keeps min-pair > r_min for N in [2,7].
    const double SPHERE_SCALE = 3.0;

    auto lj_ar = find_lj("Ar");
    const double r_min = lj_ar ? lj_ar->r_min : 3.817;

    g_report << "\n[Suite G] Noble Gas Cluster FIRE (Ar2-Ar7)\n";
    std::printf("\n--- Suite G: Noble Gas Cluster FIRE ---\n");

    FIREParams fp;
    fp.dt        = 0.005;
    fp.dt_max    = 0.10;
    fp.max_steps = 50000;
    fp.epsF      = 1e-5;
    fp.epsU      = 1e-12;

    for (int N = 2; N <= 7; ++N) {
        // Fibonacci sphere — deterministic, places all pairs at > r_min
        vsepr::io::XYZMolecule m;
        const double R            = r_min * std::sqrt(static_cast<double>(N)) / SPHERE_SCALE;
        const double golden_angle = M_PI * (3.0 - std::sqrt(5.0));
        for (int i = 0; i < N; ++i) {
            double t   = N > 1 ? (2.0*i + 1.0)/N - 1.0 : 0.0;
            double r_h = std::sqrt(std::max(0.0, 1.0 - t*t));
            double phi = golden_angle * i;
            m.atoms.emplace_back("Ar",
                R * r_h * std::cos(phi),
                R * r_h * std::sin(phi),
                R * t);
        }

        State s = parse(m);
        model.eval(s, mp);
        double U0   = s.E.total();
        double nn0  = nn_dist(s);

        FIRE fire(model, mp);
        auto  st        = fire.minimize(s, fp);
        double nn_final = nn_dist(s);

        std::string tag = "Ar" + std::to_string(N);

        // --- Layer 1: basic descent -----------------------------------------
        check(std::isfinite(st.U), tag + ": energy finite");
        check(st.U < U0,           tag + ": energy decreased",
              "U0=" + std::to_string(U0).substr(0,7) +
              " U=" + std::to_string(st.U).substr(0,7));

        // --- Layer 2: convergence quality ------------------------------------
        check(st.Frms < FRMS_TOL,
              tag + ": Frms converged",
              "Frms=" + std::to_string(st.Frms).substr(0,8) +
              " tol=" + std::to_string(FRMS_TOL));
        check(nn_final > OVERLAP_FRAC * r_min,
              tag + ": no atom overlap",
              "nn=" + std::to_string(nn_final).substr(0,6) +
              " min=" + std::to_string(OVERLAP_FRAC * r_min).substr(0,5));
        check(st.dU_per_atom < STAGNATION_EP,
              tag + ": energy not stagnating",
              "dU/atom=" + std::to_string(st.dU_per_atom).substr(0,8));

        if (g_verbose)
            std::printf("    Ar%d: nn0=%.3f U0=%.4f U=%.4f "
                        "Frms=%.2e dU/N=%.2e steps=%d\n",
                        N, nn0, U0, st.U, st.Frms, st.dU_per_atom, st.step);
    }
}

// ============================================================================
// H. Dielectric Screening Ratio Verification
// ============================================================================

static void suite_H(IModel& model)
{
    g_report << "\n[Suite H] Dielectric Screening\n";
    std::printf("\n--- Suite H: Dielectric Screening ---\n");

    double dielectrics[] = {1.0, 2.0, 4.0, 10.0, 20.0, 40.0, 78.4};
    int n_eps = sizeof(dielectrics) / sizeof(dielectrics[0]);

    vsepr::io::XYZMolecule m;
    m.atoms.emplace_back("Na", 0.0, 0.0, 0.0);
    m.atoms.emplace_back("Cl", 5.0, 0.0, 0.0);

    // Get vacuum reference
    State s_vac = parse(m);
    s_vac.Q[0] = +1.0; s_vac.Q[1] = -1.0;
    ModelParams mp_vac; mp_vac.rc = 20.0;
    mp_vac.env = EnvironmentContext::near_vacuum();
    model.eval(s_vac, mp_vac);
    double U_vac = s_vac.E.UCoul;

    for (int i = 0; i < n_eps; ++i) {
        double eps = dielectrics[i];
        State s = parse(m);
        s.Q[0] = +1.0; s.Q[1] = -1.0;
        ModelParams mp_s; mp_s.rc = 20.0;
        mp_s.env = EnvironmentContext::solution(eps);
        model.eval(s, mp_s);

        double ratio = U_vac / s.E.UCoul;
        double err = std::abs(ratio - eps);

        check(err < 0.01, "eps_r=" + std::to_string((int)eps) + " screening",
              "ratio=" + std::to_string(ratio).substr(0,6));
    }
}

// ============================================================================
// N. Restoring-Force Scan (bond stretch / compression)
// ============================================================================

static void suite_N(IModel& model, const ModelParams& mp)
{
    g_report << "\n[Suite N] Restoring Force Scan\n";
    std::printf("\n--- Suite N: Restoring Force Scan ---\n");

    // For each noble-gas homonuclear dimer, sweep displacements δ from r_min
    // in both directions (compression: r < r_min, extension: r > r_min).
    //
    // Two physical checks:
    //   N1. Restoring direction: F_x on atom 0 must satisfy F_x * δ > 0
    //       (sign of force matches sign of displacement from equilibrium).
    //       Derivation: F_x = +dU/dr; at r < r_min, dU/dr < 0 → F_x * (r-r_min) > 0.
    //
    //   N2. r_min is an energy minimum: U(r_min + δ) > U(r_min) for all δ ≠ 0.
    //       This directly verifies the analytic r_min value against the model.

    struct Pair { const char* sym; };
    Pair pairs[] = {{"He"},{"Ne"},{"Ar"},{"Kr"},{"Xe"}};

    const double DELTAS[] = {-1.5,-1.0,-0.6,-0.3, 0.3, 0.6, 1.0, 1.5};
    const int    N_DELTAS = (int)(sizeof(DELTAS)/sizeof(DELTAS[0]));

    for (auto& p : pairs) {
        auto lj = find_lj(p.sym);
        if (!lj) { skip(std::string(p.sym) + " restoring force", "no LJ params"); continue; }

        double r_min_p = lj->r_min;
        bool dir_ok    = true;
        bool min_ok    = true;

        // Evaluate energy at exact r_min
        ModelParams mpr = mp; mpr.rc = r_min_p * 4.0 + 2.0;
        auto eval_U = [&](double r) -> double {
            vsepr::io::XYZMolecule m;
            m.atoms.emplace_back(p.sym, 0.0, 0.0, 0.0);
            m.atoms.emplace_back(p.sym, r,   0.0, 0.0);
            State s = parse(m);
            model.eval(s, mpr);
            return s.E.total();
        };
        double U_min = eval_U(r_min_p);

        for (int k = 0; k < N_DELTAS; ++k) {
            double delta = DELTAS[k];
            double r     = r_min_p + delta;
            if (r < 0.5) continue;

            vsepr::io::XYZMolecule m;
            m.atoms.emplace_back(p.sym, 0.0, 0.0, 0.0);
            m.atoms.emplace_back(p.sym, r,   0.0, 0.0);
            State s = parse(m);
            model.eval(s, mpr);
            double Fx = s.F[0].x;
            double U  = s.E.total();

            // N1: restoring direction
            if (std::abs(delta) > 0.01) {
                bool restoring = (Fx * delta) > 0.0;
                if (!restoring) {
                    dir_ok = false;
                    if (g_verbose)
                        std::printf("    [BAD dir] %s δ=%.2f r=%.3f Fx=%.4f\n",
                                    p.sym, delta, r, Fx);
                }
            }

            // N2: energy minimum at r_min
            if (U < U_min - 1e-8) {
                min_ok = false;
                if (g_verbose)
                    std::printf("    [BAD min] %s δ=%.2f U=%.6f < U_min=%.6f\n",
                                p.sym, delta, U, U_min);
            }
        }

        check(dir_ok,  std::string(p.sym) + "2: restoring force direction");
        check(min_ok,  std::string(p.sym) + "2: r_min is energy minimum");
    }
}

// ============================================================================
// Q. Crystal Builder Fidelity + NaCl FIRE Relaxation
// ============================================================================

static void suite_Q(IModel& model)
{
    g_report << "\n[Suite Q] Crystal Builder Fidelity + NaCl Relaxation\n";
    std::printf("\n--- Suite Q: Crystal Builder Fidelity ---\n");

    // For all presets: verify 2x2x2 supercell atom count and initial nn geometry.
    // FIRE relaxation is intentionally omitted for all four crystals:
    //   - Cu, Fe, Si: actual bond lengths << UFF LJ r_min (repulsive wall at crystal geometry)
    //   - NaCl: Coulomb dominates energy but UFF LJ still pushes ions apart;
    //           the model minimum differs from the physical crystal, so FIRE
    //           would increase energy from the Wyckoff starting point.
    // The builder correctness check (atom count + nn) is the appropriate scope here.

    struct CrystalCase {
        const char* name;
        UnitCell (*factory)();
        bool fire;
    };
    CrystalCase cases[] = {
        {"Cu",   presets::copper_fcc,       false},
        {"Fe",   presets::iron_bcc,         false},
        {"NaCl", presets::sodium_chloride,  false},
        {"Si",   presets::silicon_diamond,  false},
    };

    FIREParams fp;
    fp.dt        = 0.003;
    fp.dt_max    = 0.05;
    fp.max_steps = 20000;
    fp.epsF      = 1e-4;
    fp.epsU      = 1e-10;

    for (auto& c : cases) {
        auto ref = find_crystal(c.name);
        if (!ref) { skip(c.name, "no crystal ref"); continue; }

        UnitCell uc    = c.factory();
        auto sc        = construct_supercell(uc, 2, 2, 2);
        uint32_t N_exp = 8u * (uint32_t)ref->Z_per_cell;
        State&   s     = sc.state;
        std::string tag = std::string(c.name) + " 2x2x2";

        // Q1: atom count is exact
        check((int)s.N == (int)N_exp, tag + ": atom count",
              "N=" + std::to_string(s.N) + " expect=" + std::to_string(N_exp));

        // Q2: initial nn from builder matches Wyckoff within 3%
        double nn0 = nn_dist(s);
        check(std::abs(nn0 - ref->nn) / ref->nn < 0.03,
              tag + ": initial nn from builder",
              "nn=" + std::to_string(nn0).substr(0,6) +
              " ref=" + std::to_string(ref->nn).substr(0,6));

        if (!c.fire) continue;

        // Q3-Q5: FIRE relaxation for NaCl (LJ + Coulomb)
        s.F.resize(s.N, {0,0,0});
        ModelParams mps; mps.rc = ref->nn * 3.0 + 1.0;
        mps.env = EnvironmentContext::near_vacuum();
        model.eval(s, mps);
        double U0 = s.E.total();

        FIRE fire(model, mps);
        auto st = fire.minimize(s, fp);

        check(std::isfinite(st.U), tag + ": energy finite after FIRE");
        check(st.U < U0,           tag + ": energy decreased under FIRE",
              "U0=" + std::to_string(U0).substr(0,8) +
              " U=" + std::to_string(st.U).substr(0,8));

        double nn_f = nn_dist(s);
        check(std::abs(nn_f - ref->nn) / ref->nn < 0.08,
              tag + ": nn within 8% of Wyckoff after FIRE",
              "nn=" + std::to_string(nn_f).substr(0,6) +
              " ref=" + std::to_string(ref->nn).substr(0,6));

        if (g_verbose)
            std::printf("    %s: U0=%.2f U=%.2f nn0=%.3f nn=%.3f ref=%.3f Frms=%.2e\n",
                        c.name, U0, st.U, nn0, nn_f, ref->nn, st.Frms);
    }
}

// ============================================================================
// I. Randomized LJ Force-Energy Consistency
// ============================================================================

static void suite_I(IModel& model, const ModelParams& mp)
{
    g_report << "\n[Suite I] Randomized LJ Force-Energy Consistency (seed="
             << g_seed << ", N=" << g_rand_iters << ")\n";
    std::printf("\n--- Suite I: Randomized LJ F-E Consistency (N=%d, seed=%llu) ---\n",
                g_rand_iters, (unsigned long long)g_seed);

    // Elements we can test (have LJ params in UFF)
    const char* pool[] = {"H","C","N","O","F","Na","Cl","Ar","Si","Fe","Cu","Kr","Xe"};
    const int   pool_n = (int)(sizeof(pool)/sizeof(pool[0]));
    double dr = 1e-6;
    int    bad = 0;
    double worst = 0;

    for (int iter = 0; iter < g_rand_iters; ++iter) {
        // Pick two random elements
        const char* sym_a = pool[rnd_int(0, pool_n-1)];
        const char* sym_b = pool[rnd_int(0, pool_n-1)];
        auto lj_a = find_lj(sym_a);
        auto lj_b = find_lj(sym_b);
        if (!lj_a || !lj_b) continue;

        // Random distance in [0.85*r_min, 2.5*r_min_a]
        double r_min_a = lj_a->r_min;
        double r = rnd_uniform(0.85*r_min_a, 2.5*r_min_a);

        ModelParams mpr = mp;
        mpr.rc = r * 3.0 + 2.0;

        vsepr::io::XYZMolecule m;
        m.atoms.emplace_back(sym_a, 0.0, 0.0, 0.0);
        m.atoms.emplace_back(sym_b, r,   0.0, 0.0);
        State s0 = parse(m); model.eval(s0, mpr);

        State sp = s0, sm = s0;
        sp.F.assign(2,{0,0,0}); sp.E = {}; sp.X[0].x += dr;
        sm.F.assign(2,{0,0,0}); sm.E = {}; sm.X[0].x -= dr;
        model.eval(sp, mpr); model.eval(sm, mpr);

        double F_num = -(sp.E.total() - sm.E.total()) / (2.0*dr);
        double F_ana = s0.F[0].x;
        double scale = std::max(std::abs(F_ana), 1e-6);
        double rel   = std::abs(F_num - F_ana) / scale;
        if (rel > worst) worst = rel;
        if (rel > 1e-3) ++bad;
    }

    check(bad == 0, "random LJ F-E: all within 1e-3",
          "worst=" + std::to_string(worst) + " bad=" + std::to_string(bad));
}

// ============================================================================
// J. Randomized Coulomb 1/r Law
// ============================================================================

static void suite_J(IModel& model)
{
    const int N = std::max(80, g_rand_iters);
    g_report << "\n[Suite J] Randomized Coulomb 1/r Law (seed=" << g_seed
             << ", N=" << N << ")\n";
    std::printf("\n--- Suite J: Randomized Coulomb 1/r (N=%d, seed=%llu) ---\n",
                N, (unsigned long long)g_seed);

    const double k_coul = 332.0636;
    int bad_mag = 0, bad_scale = 0;
    double worst_rel = 0;

    for (int iter = 0; iter < N; ++iter) {
        double q1 = rnd_uniform(-2.0, 2.0);
        double q2 = rnd_uniform(-2.0, 2.0);
        double r1 = rnd_uniform(2.0, 14.0);
        double r2 = rnd_uniform(2.0, 14.0);

        ModelParams mpr; mpr.rc = 20.0;
        mpr.env = EnvironmentContext::near_vacuum();

        auto make = [&](double r, double qa, double qb) -> double {
            vsepr::io::XYZMolecule m;
            m.atoms.emplace_back("Na", 0.0, 0.0, 0.0);
            m.atoms.emplace_back("Cl", r,   0.0, 0.0);
            State s = parse(m);
            s.Q[0] = qa; s.Q[1] = qb;
            model.eval(s, mpr);
            return s.E.UCoul;
        };

        double U1 = make(r1, q1, q2);
        double U2 = make(r2, q1, q2);
        double U_expect1 = k_coul * q1 * q2 / r1;
        double U_expect2 = k_coul * q1 * q2 / r2;

        double rel1 = (std::abs(U_expect1) > 1e-12)
                      ? std::abs(U1 - U_expect1) / std::abs(U_expect1) : 0.0;
        double rel2 = (std::abs(U_expect2) > 1e-12)
                      ? std::abs(U2 - U_expect2) / std::abs(U_expect2) : 0.0;
        if (rel1 > worst_rel) worst_rel = rel1;
        if (rel2 > worst_rel) worst_rel = rel2;
        if (rel1 > 1e-6 || rel2 > 1e-6) ++bad_mag;

        // 1/r scaling: U(r1)/U(r2) should equal r2/r1
        if (std::abs(q1*q2) > 0.01 && std::abs(U2) > 1e-12) {
            double ratio_calc  = U1 / U2;
            double ratio_exact = r2 / r1;
            if (std::abs(ratio_calc - ratio_exact) > 1e-5) ++bad_scale;
        }
    }

    check(bad_mag   == 0, "random Coulomb: magnitude U=kqq/r",
          "worst_rel=" + std::to_string(worst_rel));
    check(bad_scale == 0, "random Coulomb: 1/r scaling");
}

// ============================================================================
// K. Randomized Dielectric Screening
// ============================================================================

static void suite_K(IModel& model)
{
    const int N = std::max(60, g_rand_iters);
    g_report << "\n[Suite K] Randomized Dielectric Sweep (N=" << N << ")\n";
    std::printf("\n--- Suite K: Randomized Dielectric (N=%d) ---\n", N);

    double r = 5.0;
    int bad = 0;
    double worst = 0;

    vsepr::io::XYZMolecule m;
    m.atoms.emplace_back("Na", 0.0, 0.0, 0.0);
    m.atoms.emplace_back("Cl", r,   0.0, 0.0);

    // Vacuum reference
    ModelParams mp_vac; mp_vac.rc = 20.0;
    mp_vac.env = EnvironmentContext::near_vacuum();
    State s_vac = parse(m); s_vac.Q[0] = +1.0; s_vac.Q[1] = -1.0;
    model.eval(s_vac, mp_vac);
    double U_vac = s_vac.E.UCoul;

    // All 19 solvents + N random continuous dielectrics
    for (int i = 0; i < N_SOLVENT_REFS; ++i) {
        double eps = SOLVENT_REFS[i].dielectric;
        if (eps < 1.001) continue;
        ModelParams mps; mps.rc = 20.0;
        mps.env = EnvironmentContext::solution(eps);
        State ss = parse(m); ss.Q[0] = +1.0; ss.Q[1] = -1.0;
        model.eval(ss, mps);
        double ratio = U_vac / ss.E.UCoul;
        double err   = std::abs(ratio - eps) / eps;
        if (err > worst) worst = err;
        if (err > 1e-4) ++bad;
    }

    for (int iter = 0; iter < N; ++iter) {
        double eps = rnd_uniform(1.5, 120.0);
        ModelParams mps; mps.rc = 20.0;
        mps.env = EnvironmentContext::solution(eps);
        State ss = parse(m); ss.Q[0] = +1.0; ss.Q[1] = -1.0;
        model.eval(ss, mps);
        double ratio = U_vac / ss.E.UCoul;
        double err   = std::abs(ratio - eps) / eps;
        if (err > worst) worst = err;
        if (err > 1e-4) ++bad;
    }

    check(bad == 0, "random dielectric: U_vac/U_eps = eps_r",
          "worst_rel=" + std::to_string(worst));
}

// ============================================================================
// L. Randomized Crystal Supercell Atom Count
// ============================================================================

static void suite_L()
{
    g_report << "\n[Suite L] Randomized Crystal Supercell Counts\n";
    std::printf("\n--- Suite L: Randomized Crystal Supercell ---\n");

    // Presets that are available
    struct Preset { const char* ref; UnitCell (*factory)(); };
    Preset presets[] = {
        {"Al",   presets::aluminum_fcc},
        {"Cu",   presets::copper_fcc},
        {"Fe",   presets::iron_bcc},
        {"NaCl", presets::sodium_chloride},
        {"Si",   presets::silicon_diamond},
        {"CsCl", presets::cesium_chloride},
    };

    // For each preset, test 12 random (n1,n2,n3) in [1,4]
    for (auto& p : presets) {
        auto ref = find_crystal(p.ref);
        if (!ref) continue;
        int  Z   = ref->Z_per_cell;
        bool all_ok = true;

        for (int trial = 0; trial < 12; ++trial) {
            int n1 = rnd_int(1,4), n2 = rnd_int(1,4), n3 = rnd_int(1,4);
            UnitCell uc = p.factory();
            auto sc = construct_supercell(uc, n1, n2, n3);
            int expected = n1 * n2 * n3 * Z;
            if ((int)sc.state.N != expected) {
                std::printf("  [FAIL]  %s %dx%dx%d: N=%u expect=%d\n",
                            p.ref, n1, n2, n3, sc.state.N, expected);
                all_ok = false;
            }
        }
        check(all_ok, std::string(p.ref) + " supercell atom counts");
    }
}

// ============================================================================
// M. NVE Energy Conservation
// ============================================================================

static void suite_M(IModel& model, const ModelParams& mp)
{
    g_report << "\n[Suite M] NVE Energy Conservation (seed=" << g_seed << ")\n";
    std::printf("\n--- Suite M: NVE Energy Conservation ---\n");

    // Test on Ar3, Ar4, Ar5 with randomized initial positions and velocities
    for (int N = 3; N <= 5; ++N) {
        vsepr::io::XYZMolecule mol;
        // Start near equilibrium spacing, add small random displacements
        auto lj_ar = find_lj("Ar");
        double r0 = lj_ar ? lj_ar->r_min : 3.82;
        for (int i = 0; i < N; ++i) {
            double angle = 2.0*M_PI*i/N;
            double x = r0 * std::cos(angle) + rnd_uniform(-0.1, 0.1);
            double y = r0 * std::sin(angle) + rnd_uniform(-0.1, 0.1);
            double z = rnd_uniform(-0.2, 0.2);
            mol.atoms.emplace_back("Ar", x, y, z);
        }
        State s = parse(mol);

        // Assign random velocities ~ Maxwell-Boltzmann at 100 K
        // k_B = 1.987e-3 kcal/(mol·K); mass Ar = 39.948 amu
        // v_rms = sqrt(3 k_B T / m) in kcal^0.5/(mol^0.5·amu^0.5)
        // In AKMA: 1 amu·(A/fs)^2 = 1 kcal/mol -> v in A/fs
        double kB_kcal = 1.987204e-3;  // kcal/(mol·K)
        double m_Ar    = 39.948;
        double T_K     = 100.0;
        double sigma_v = std::sqrt(kB_kcal * T_K / m_Ar);
        s.V.resize(N);
        std::normal_distribution<double> vnorm(0.0, sigma_v);
        for (int i = 0; i < N; ++i)
            s.V[i] = {vnorm(g_rng), vnorm(g_rng), vnorm(g_rng)};

        // Evaluate initial energy
        ModelParams mpr = mp; mpr.rc = 14.0;
        model.eval(s, mpr);
        double KE0 = 0;
        for (int i = 0; i < N; ++i) {
            auto& v = s.V[i];
            KE0 += 0.5 * m_Ar * (v.x*v.x + v.y*v.y + v.z*v.z);
        }
        double E0 = s.E.total() + KE0;

        // 200 NVE velocity-Verlet steps
        double dt = 0.001; // fs
        double max_drift = 0.0;
        bool   finite_ok = true;
        for (int step = 0; step < 200; ++step) {
            // half kick
            for (int i = 0; i < N; ++i) {
                s.V[i].x += 0.5*dt * s.F[i].x / m_Ar;
                s.V[i].y += 0.5*dt * s.F[i].y / m_Ar;
                s.V[i].z += 0.5*dt * s.F[i].z / m_Ar;
            }
            // drift
            for (int i = 0; i < N; ++i) {
                s.X[i].x += dt * s.V[i].x;
                s.X[i].y += dt * s.V[i].y;
                s.X[i].z += dt * s.V[i].z;
            }
            // re-eval forces
            s.F.assign(N, {0,0,0}); s.E = {};
            model.eval(s, mpr);
            // second half kick
            for (int i = 0; i < N; ++i) {
                s.V[i].x += 0.5*dt * s.F[i].x / m_Ar;
                s.V[i].y += 0.5*dt * s.F[i].y / m_Ar;
                s.V[i].z += 0.5*dt * s.F[i].z / m_Ar;
            }
            // KE
            double KE = 0;
            for (int i = 0; i < N; ++i) {
                auto& v = s.V[i];
                KE += 0.5 * m_Ar * (v.x*v.x + v.y*v.y + v.z*v.z);
            }
            double E_now = s.E.total() + KE;
            if (!std::isfinite(E_now)) { finite_ok = false; break; }
            double drift = std::abs(E_now - E0) / (std::abs(E0) + 1e-12);
            if (drift > max_drift) max_drift = drift;
        }

        std::string tag = "Ar" + std::to_string(N) + " NVE";
        check(finite_ok, tag + ": energy finite");
        check(max_drift < 1e-3, tag + ": energy conserved",
              "max_drift=" + std::to_string(max_drift));
        if (g_verbose)
            std::printf("    Ar%d: E0=%.4f  max_drift=%.2e\n", N, E0, max_drift);
    }
}

// ============================================================================
// P. Downloaded References (PubChem + NIST)
// ============================================================================

static void suite_P(IModel& model, const ModelParams& mp)
{
    (void)model; (void)mp;  // used only when HAS_DOWNLOADED_REFS
    g_report << "\n[Suite P] Downloaded Reference Verification\n";
    std::printf("\n--- Suite P: Downloaded References ---\n");

#if HAS_DOWNLOADED_REFS
    std::printf("  %d bond refs, %d crystal refs, %d diatomic refs, %d solvent refs\n",
                N_DOWNLOADED_BOND_REFS, N_DOWNLOADED_CRYSTAL_REFS,
                N_DOWNLOADED_DIATOMIC_REFS, N_DOWNLOADED_SOLVENT_REFS);

    // P1: Verify all downloaded bond lengths are physically sane
    for (int i = 0; i < N_DOWNLOADED_BOND_REFS; ++i) {
        const auto& b = DOWNLOADED_BOND_REFS[i];
        check(b.r_eq > 0.4 && b.r_eq < 5.0,
              std::string("downloaded bond ") + b.formula + " " + b.bond + ": r in [0.4,5.0]A",
              "r=" + std::to_string(b.r_eq));
    }

    // P2: Verify all downloaded diatomic r_e match our BOND_REFS within tolerance
    int matched = 0;
    for (int i = 0; i < N_DOWNLOADED_DIATOMIC_REFS; ++i) {
        const auto& d = DOWNLOADED_DIATOMIC_REFS[i];
        // Find matching entry in BOND_REFS
        for (int j = 0; j < N_BOND_REFS; ++j) {
            if (std::string(BOND_REFS[j].formula) == d.formula) {
                double err = std::abs(BOND_REFS[j].r_eq - d.r_eq);
                check(err < 0.02,
                      std::string("diatomic cross-check ") + d.formula + " " + d.bond,
                      "hardcoded=" + std::to_string(BOND_REFS[j].r_eq).substr(0,6) +
                      " downloaded=" + std::to_string(d.r_eq).substr(0,6));
                ++matched;
                break;
            }
        }
    }

    // P3: Solvent dielectric Coulomb ratio check for each downloaded solvent
    vsepr::io::XYZMolecule m_ion;
    m_ion.atoms.emplace_back("Na", 0.0, 0.0, 0.0);
    m_ion.atoms.emplace_back("Cl", 5.0, 0.0, 0.0);
    ModelParams mp_vac; mp_vac.rc = 20.0;
    mp_vac.env = EnvironmentContext::near_vacuum();
    State s_vac = parse(m_ion); s_vac.Q[0] = +1.0; s_vac.Q[1] = -1.0;
    model.eval(s_vac, mp_vac);
    double U_vac = s_vac.E.UCoul;

    for (int i = 0; i < N_DOWNLOADED_SOLVENT_REFS; ++i) {
        const auto& sv = DOWNLOADED_SOLVENT_REFS[i];
        if (sv.dielectric < 1.5) continue;
        ModelParams mps; mps.rc = 20.0;
        mps.env = EnvironmentContext::solution(sv.dielectric);
        State ss = parse(m_ion); ss.Q[0]=+1.0; ss.Q[1]=-1.0;
        model.eval(ss, mps);
        double ratio = U_vac / ss.E.UCoul;
        double err = std::abs(ratio - sv.dielectric) / sv.dielectric;
        check(err < 1e-4,
              std::string("downloaded solvent ") + sv.name + " screening",
              "eps=" + std::to_string(sv.dielectric).substr(0,6) +
              " ratio=" + std::to_string(ratio).substr(0,6));
    }

#else
    skip("downloaded bond refs",     "run scripts/fetch_empirical.py first");
    skip("downloaded diatomic refs", "run scripts/fetch_empirical.py first");
    skip("downloaded solvent refs",  "run scripts/fetch_empirical.py first");
#endif
}

// ============================================================================
// main
// ============================================================================

int main(int argc, char* argv[])
{
    g_seed = static_cast<uint64_t>(std::time(nullptr));

    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--verbose") == 0) {
            g_verbose = true;
        } else if (std::strcmp(argv[i], "--seed") == 0 && i+1 < argc) {
            g_seed = static_cast<uint64_t>(std::atoll(argv[++i]));
        } else if (std::strcmp(argv[i], "--rand-iters") == 0 && i+1 < argc) {
            g_rand_iters = std::atoi(argv[++i]);
        }
    }
    g_rng.seed(g_seed);

    std::printf("\n");
    std::printf("=============================================================\n");
    std::printf("  Deep Verification Suite\n");
    std::printf("  Static DB: %d bonds, %d angles, %d crystals,\n",
                N_BOND_REFS, N_ANGLE_REFS, N_CRYSTAL_REFS);
    std::printf("             %d LJ, %d diatomics, %d solvents, %d ions\n",
                N_LJ_REFS, N_DIATOMIC_REFS, N_SOLVENT_REFS, N_ION_REFS);
    std::printf("  Random:    seed=%llu  rand_iters=%d\n",
                (unsigned long long)g_seed, g_rand_iters);
#if HAS_DOWNLOADED_REFS
    std::printf("  Downloaded: %d bonds, %d crystals, %d diatomics, %d solvents\n",
                N_DOWNLOADED_BOND_REFS, N_DOWNLOADED_CRYSTAL_REFS,
                N_DOWNLOADED_DIATOMIC_REFS, N_DOWNLOADED_SOLVENT_REFS);
#else
    std::printf("  Downloaded: not present (run scripts/fetch_empirical.py)\n");
#endif
    std::printf("=============================================================\n");

    mkdir_p("verification/deep");

    auto model = create_lj_coulomb_model();
    ModelParams mp; mp.rc = 12.0;

    // Static suites
    suite_A(*model, mp);
    suite_B(*model, mp);
    suite_C(*model, mp);
    suite_D();
    suite_E();
    suite_F();
    suite_G(*model, mp);
    suite_H(*model);
    suite_N(*model, mp);
    suite_Q(*model);

    // Randomized suites
    suite_I(*model, mp);
    suite_J(*model);
    suite_K(*model);
    suite_L();
    suite_M(*model, mp);

    // Downloaded reference suite
    suite_P(*model, mp);

    // Summary
    int total = g_pass + g_fail + g_skip;
    std::printf("\n=============================================================\n");
    std::printf("  Deep Verification:  %d total,  %d passed,  %d failed,  %d skipped\n",
                total, g_pass, g_fail, g_skip);
    std::printf("  Seed: %llu  (re-run with --seed %llu to reproduce)\n",
                (unsigned long long)g_seed, (unsigned long long)g_seed);
    std::printf("=============================================================\n\n");

    // Write artifacts
    {
        std::ofstream f("verification/deep/report.txt");
        f << "Deep Verification Report\n";
        f << "========================\n\n";
        f << "Seed:    " << g_seed << "\n";
        f << "Passed:  " << g_pass << "\n";
        f << "Failed:  " << g_fail << "\n";
        f << "Skipped: " << g_skip << "\n\n";
        f << g_report.str();
    }
    {
        std::ofstream f("verification/deep/status.txt");
        f << (g_fail == 0 ? "PASS" : "FAIL") << "\n";
        f << "Seed:    " << g_seed << "\n";
        f << "Passed:  " << g_pass << "\n";
        f << "Failed:  " << g_fail << "\n";
        f << "Skipped: " << g_skip << "\n";
    }

    return g_fail > 0 ? 1 : 0;
}
