#!/usr/bin/env python3
"""
bond_graph_auto.py  --  VSEPR-SIM Bond Graph Automation Orchestrator
=====================================================================
One-command launcher that wires the full bond graph pipeline:

  1. Generates a .vsim script for a given molecule (or picks one at random)
  2. Starts viz_web.py in the background (if not already running)
  3. Starts bond_graph_randomizer.py in the background (continuous stream)
  4. Opens http://localhost:<port>/graph in the default browser
  5. Optionally runs vsepr.exe on the generated script (--run-sim)

Usage
-----
  python tools/bond_graph_auto.py
  python tools/bond_graph_auto.py --formula CH4
  python tools/bond_graph_auto.py --formula C6H6 --run-sim
  python tools/bond_graph_auto.py --no-browser --no-randomizer --verbose

Options
-------
  --formula FORMULA     Molecule formula for the .vsim script
                        (default: random pick from built-in library)
  --name NAME           Project name written into the .vsim file
                        (default: derived from formula)
  --port PORT           viz_web.py HTTP port                  (default: 8899)
  --run-sim             Also launch vsepr.exe on the script
  --no-browser          Do not open the browser
  --no-randomizer       Do not start the randomizer background stream
  --randomizer-mode M   xyz | generate  passed to randomizer  (default: xyz)
  --interval SECONDS    Randomizer interval                   (default: 3.0)
  --out-dir DIR         Directory for generated .vsim files
                        (default: examples/)
  --seed N              Seed for the .vsim script             (default: random)
  --verbose             Extra diagnostic output

VSEPR-SIM v5.1.4  |  tools/bond_graph_auto.py
"""

import sys
import os
import json
import time
import socket
import argparse
import random
import subprocess
import threading
import webbrowser
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

TOOLS_DIR  = Path(__file__).resolve().parent
WORKSPACE  = TOOLS_DIR.parent
BUILD_DIR  = WORKSPACE / "build"
BIN_DIR    = WORKSPACE / "bin"

VIZ_WEB_SCRIPT    = TOOLS_DIR / "viz_web.py"
RANDOMIZER_SCRIPT = TOOLS_DIR / "bond_graph_randomizer.py"

# Preferred vsepr.exe resolution order
VSEPR_CANDIDATES = [
    BUILD_DIR / "vsepr.exe",
    BIN_DIR   / "vsepr.exe",
    WORKSPACE / "vsepr.exe",
]

PYTHON_EXE = sys.executable

# ---------------------------------------------------------------------------
# Built-in molecule library (formula -> simulation preset)
# ---------------------------------------------------------------------------

MOLECULE_LIBRARY = {
    "H2O":    {"preset": "gas",     "box": 20.0, "temp": 300.0},
    "CH4":    {"preset": "gas",     "box": 25.0, "temp": 300.0},
    "CO2":    {"preset": "gas",     "box": 25.0, "temp": 300.0},
    "NH3":    {"preset": "gas",     "box": 25.0, "temp": 300.0},
    "C6H6":   {"preset": "gas",     "box": 30.0, "temp": 298.0},
    "C2H5OH": {"preset": "gas",     "box": 30.0, "temp": 298.0},
    "SF6":    {"preset": "gas",     "box": 28.0, "temp": 300.0},
    "NO2":    {"preset": "gas",     "box": 22.0, "temp": 300.0},
    "SO3":    {"preset": "gas",     "box": 22.0, "temp": 300.0},
    "N2":     {"preset": "gas",     "box": 25.0, "temp": 300.0},
    "O2":     {"preset": "gas",     "box": 25.0, "temp": 300.0},
    "HCl":    {"preset": "gas",     "box": 20.0, "temp": 300.0},
    "NaCl":   {"preset": "crystal", "box": 30.0, "temp": 300.0},
    "Au2":    {"preset": "metal",   "box": 25.0, "temp": 300.0},
    "Fe2":    {"preset": "metal",   "box": 25.0, "temp": 300.0},
}

# ---------------------------------------------------------------------------
# .vsim script template
# ---------------------------------------------------------------------------

VSIM_TEMPLATE = """\
# {name}.vsim
# Auto-generated by bond_graph_auto.py
# VSEPR-SIM v5.1.4

[project]
name        = "{name}"
version     = "v5.1.4"
seed_base   = {seed}
determinism = false
description = "Bond graph demo: {formula}"

[simulation]
molecules           = {formula}:{count}
fire_max_steps      = 300
fire_dt_fs          = 1.0
box_size_ang        = {box}
periodic            = false
formation_preset    = {preset}
step_delay_ms       = 0

[export]
write_xyz = true

[export.visual]
show_bond_graph = true
bond_graph_port = {port}
"""

# ---------------------------------------------------------------------------
# ANSI helpers
# ---------------------------------------------------------------------------

_ANSI = sys.platform != "win32" or os.environ.get("TERM")
def _c(code, s): return f"\033[{code}m{s}\033[0m" if _ANSI else s
YEL  = lambda s: _c("93", s)
GRN  = lambda s: _c("92", s)
CYN  = lambda s: _c("96", s)
RED  = lambda s: _c("91", s)
DIM  = lambda s: _c("2",  s)
BOLD = lambda s: _c("1",  s)

def log(msg):      print(f"  {msg}")
def ok(msg):       print(f"  {GRN('[OK]')}  {msg}")
def info(msg):     print(f"  {CYN('[..]')}  {msg}")
def warn(msg):     print(f"  {YEL('[!]')}   {msg}")
def err(msg):      print(f"  {RED('[ERR]')} {msg}", file=sys.stderr)

# ---------------------------------------------------------------------------
# Server probe
# ---------------------------------------------------------------------------

def server_is_up(host, port, timeout=1.0):
    """Return True if something is listening on host:port."""
    try:
        s = socket.create_connection((host, port), timeout=timeout)
        s.close()
        return True
    except (ConnectionRefusedError, OSError):
        return False

def wait_for_server(host, port, timeout=30, interval=0.5):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if server_is_up(host, port):
            return True
        time.sleep(interval)
    return False

# ---------------------------------------------------------------------------
# Find vsepr.exe
# ---------------------------------------------------------------------------

def find_vsepr():
    for p in VSEPR_CANDIDATES:
        if p.exists():
            return p
    return None

# ---------------------------------------------------------------------------
# Generate .vsim script
# ---------------------------------------------------------------------------

def make_vsim(formula, name, seed, port, out_dir):
    mol = MOLECULE_LIBRARY.get(formula, {
        "preset": "gas", "box": 30.0, "temp": 300.0
    })
    content = VSIM_TEMPLATE.format(
        name    = name,
        formula = formula,
        count   = 1,
        seed    = seed,
        box     = mol["box"],
        preset  = mol["preset"],
        port    = port,
    )
    out_path = Path(out_dir) / f"{name}.vsim"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path

# ---------------------------------------------------------------------------
# Start viz_web.py
# ---------------------------------------------------------------------------

def start_viz_web(host, port, verbose):
    info(f"Starting viz_web.py on port {port} ...")
    flags = ["--verbose"] if verbose else []
    proc = subprocess.Popen(
        [PYTHON_EXE, str(VIZ_WEB_SCRIPT), "--http-port", str(port)] + flags,
        stdout=subprocess.DEVNULL if not verbose else None,
        stderr=subprocess.DEVNULL if not verbose else None,
        cwd=str(WORKSPACE),
    )
    if wait_for_server(host, port, timeout=30):
        ok(f"viz_web.py up at http://{host}:{port}")
        return proc
    else:
        err("viz_web.py did not come up within 30 s")
        proc.terminate()
        return None

# ---------------------------------------------------------------------------
# Start randomizer
# ---------------------------------------------------------------------------

def start_randomizer(mode, interval, verbose):
    info(f"Starting bond_graph_randomizer.py  (mode={mode}, interval={interval}s) ...")
    flags = ["--verbose"] if verbose else []
    proc = subprocess.Popen(
        [PYTHON_EXE, str(RANDOMIZER_SCRIPT),
         "--mode", mode,
         "--interval", str(interval)] + flags,
        cwd=str(WORKSPACE),
    )
    ok("Randomizer running")
    return proc

# ---------------------------------------------------------------------------
# Run simulation
# ---------------------------------------------------------------------------

def run_sim(vsim_path, verbose):
    vsepr = find_vsepr()
    if not vsepr:
        warn("vsepr.exe not found -- skipping simulation run")
        return None
    info(f"Running {vsepr.name} on {vsim_path.name} ...")
    proc = subprocess.Popen(
        [str(vsepr), "run", str(vsim_path)],
        cwd=str(WORKSPACE),
        stdout=None if verbose else subprocess.DEVNULL,
        stderr=None,
    )
    return proc

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="VSEPR-SIM Bond Graph Auto-Launcher",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--formula",         default="",
                    help="molecule formula (default: random)")
    ap.add_argument("--name",            default="",
                    help="project name for the .vsim script")
    ap.add_argument("--port",            type=int, default=8899,
                    help="viz_web.py HTTP port (default: 8899)")
    ap.add_argument("--run-sim",         action="store_true",
                    help="run vsepr.exe on the generated script")
    ap.add_argument("--no-browser",      action="store_true")
    ap.add_argument("--no-randomizer",   action="store_true")
    ap.add_argument("--randomizer-mode", choices=["xyz", "generate"],
                    default="xyz")
    ap.add_argument("--interval",        type=float, default=3.0,
                    help="randomizer interval in seconds (default: 3.0)")
    ap.add_argument("--out-dir",         default="examples",
                    help="directory for generated .vsim (default: examples/)")
    ap.add_argument("--seed",            type=int, default=0,
                    help="seed_base for .vsim (default: random)")
    ap.add_argument("--verbose",         action="store_true")
    args = ap.parse_args()

    host = "localhost"
    url  = f"http://{host}:{args.port}/graph"

    # ── Header ────────────────────────────────────────────────────────────
    print(f"\n  {BOLD(YEL('VSEPR-SIM'))}  Bond Graph Auto-Launcher")
    print(f"  {'─'*46}")

    # ── Formula ───────────────────────────────────────────────────────────
    formula = args.formula.strip()
    if not formula:
        formula = random.choice(list(MOLECULE_LIBRARY.keys()))
        info(f"No formula given — picked {YEL(formula)} at random")
    else:
        info(f"Formula : {YEL(formula)}")

    name = args.name.strip() or f"bond_graph_{formula.lower()}"
    seed = args.seed or random.randint(1, 99999)

    # ── Generate .vsim ────────────────────────────────────────────────────
    out_dir  = WORKSPACE / args.out_dir
    vsim_path = make_vsim(formula, name, seed, args.port, out_dir)
    ok(f"Script   : {DIM(str(vsim_path.relative_to(WORKSPACE)))}")

    # ── Start viz_web.py ──────────────────────────────────────────────────
    viz_proc = None
    if server_is_up(host, args.port):
        ok(f"viz_web.py already running on port {args.port}")
    else:
        viz_proc = start_viz_web(host, args.port, args.verbose)
        if not viz_proc:
            sys.exit(1)

    # ── Start randomizer ──────────────────────────────────────────────────
    rand_proc = None
    if not args.no_randomizer:
        rand_proc = start_randomizer(args.randomizer_mode, args.interval, args.verbose)

    # ── Open browser ──────────────────────────────────────────────────────
    if not args.no_browser:
        time.sleep(0.8)   # let server settle
        info(f"Opening {CYN(url)} ...")
        webbrowser.open(url)
        ok("Browser opened")

    # ── Run simulation ────────────────────────────────────────────────────
    sim_proc = None
    if args.run_sim:
        sim_proc = run_sim(vsim_path, args.verbose)
        if sim_proc:
            ok(f"Simulation running (PID {sim_proc.pid})")

    # ── Status summary ────────────────────────────────────────────────────
    print(f"\n  {'─'*46}")
    print(f"  {BOLD('Viewer')}   : {CYN(url)}")
    print(f"  {BOLD('Script')}   : {DIM(str(vsim_path.relative_to(WORKSPACE)))}")
    print(f"  {BOLD('Formula')}  : {YEL(formula)}  (seed {seed})")
    if not args.no_randomizer:
        print(f"  {BOLD('Randomizer')}: streaming every {args.interval}s  (mode={args.randomizer_mode})")
    print(f"\n  Press {BOLD('Ctrl+C')} to stop all processes.\n")

    # ── Keep alive until Ctrl-C ───────────────────────────────────────────
    procs = [p for p in [viz_proc, rand_proc, sim_proc] if p is not None]
    try:
        while True:
            time.sleep(1)
            # Check if any child crashed
            for p in procs:
                if p.poll() is not None and p.returncode != 0:
                    warn(f"Process {p.pid} exited with code {p.returncode}")
    except KeyboardInterrupt:
        print(f"\n  Shutting down ...")
        for p in procs:
            try:
                p.terminate()
            except Exception:
                pass
        for p in procs:
            try:
                p.wait(timeout=3)
            except Exception:
                pass
        print(f"  {GRN('Done.')}\n")


if __name__ == "__main__":
    main()