// src/v4/uff/uff_provenance_writer.hpp
// Formation Engine v4.1.0 -- UFF provenance and validation log writer
//
// Output files (written to the output/ directory):
//   uff_autocreate_log.csv    -- tabular summary of generated/fallback entries
//   uff_provenance_log.jsonl  -- full per-parameter provenance records
//   uff_validation_log.csv    -- tabular spot-check results
//
// CSV = compact tables for quick inspection
// JSONL = detailed provenance records for audit/rebuild
//
// The writer is not thread-safe with respect to concurrent open() calls,
// but individual append_*() calls are guarded by a mutex.

#pragma once

#include "uff_table.hpp"
#include <string>
#include <fstream>
#include <mutex>
#include <chrono>

namespace vsepr::uff {

// ---------------------------------------------------------------------------
// Spot-check result record (written to uff_validation_log.csv)
// ---------------------------------------------------------------------------

struct SpotCheckResult {
	std::string test_id;
	std::string molecule;
	bool        passed        = false;
	int         missing_count = 0;
	std::string notes;
};

// ---------------------------------------------------------------------------
// UFFProvenanceWriter
// ---------------------------------------------------------------------------

class UFFProvenanceWriter {
public:
	// Construct with the output directory path (e.g. "output").
	// Files are opened/created on the first write.
	explicit UFFProvenanceWriter(std::string output_dir = "output");
	~UFFProvenanceWriter();

	// Append one row to uff_autocreate_log.csv.
	// Call this for every entry generated by UFFAutoCreator.
	void write_generated_record(const UFFEntry& entry);

	// Append one JSON object to uff_provenance_log.jsonl.
	// Call this for EVERY inserted entry (reference or generated).
	void write_provenance_record(const UFFEntry& entry);

	// Append one row to uff_validation_log.csv.
	// Call this after each spot-check run.
	void write_validation_record(const SpotCheckResult& result);

	// Flush all open streams.
	void flush();

private:
	std::string   output_dir_;
	std::mutex    mutex_;

	std::ofstream autocreate_csv_;
	std::ofstream provenance_jsonl_;
	std::ofstream validation_csv_;

	bool autocreate_header_written_   = false;
	bool validation_header_written_   = false;

	void ensure_autocreate_open_();
	void ensure_provenance_open_();
	void ensure_validation_open_();

	static std::string timestamp_utc_();
	static std::string escape_json_string_(const std::string& s);
};

} // namespace vsepr::uff
