# Active VTK + Qt3D visualization build. OpenGL/GLFW/GLEW/ImGui/BGFX are not active dependencies.
set(VSEPR_VIS_READY OFF)
if(BUILD_VIS)
    find_package(Qt6 COMPONENTS Core Gui Widgets 3DCore 3DRender 3DExtras QUIET)
    find_package(VTK COMPONENTS CommonCore CommonDataModel QUIET)
    if(NOT Qt6_3DCore_FOUND OR NOT Qt6_3DRender_FOUND OR NOT Qt6_3DExtras_FOUND)
        message(WARNING "BUILD_VIS=ON but Qt6 Qt3D components are unavailable. The VTK + Qt3D vsepr-view target is disabled; no OpenGL fallback is configured.")
    elseif(NOT VTK_FOUND)
        message(WARNING "BUILD_VIS=ON but VTK CommonCore/CommonDataModel is unavailable. The VTK + Qt3D vsepr-view target is disabled; no OpenGL fallback is configured.")
    else()
        set(VSEPR_VIS_READY ON)
    endif()
endif()
if(VSEPR_VIS_READY AND BUILD_APPS)
    add_executable(vsepr-view apps/vtk_qt3d_multiscale_viewer.cpp)
    target_include_directories(vsepr-view PRIVATE ${PROJECT_SOURCE_DIR}/include)
    target_link_libraries(vsepr-view PRIVATE Qt6::Core Qt6::Gui Qt6::Widgets Qt6::3DCore Qt6::3DRender Qt6::3DExtras VTK::CommonCore VTK::CommonDataModel)
    if(VSEPR_HAS_CUDA)
        target_compile_definitions(vsepr-view PRIVATE VSEPR_HAS_CUDA)
    endif()
    vtk_module_autoinit(TARGETS vsepr-view MODULES VTK::CommonCore VTK::CommonDataModel)
    install(TARGETS vsepr-view DESTINATION bin)
endif()
message(STATUS "")
message(STATUS "=== Active Visualization Stack ===")
if(VSEPR_VIS_READY AND TARGET vsepr-view)
    message(STATUS "  Live viewer: ON  -- vsepr-view (VTK + Qt3D, snapshot-derived)")
else()
    message(STATUS "  Live viewer: OFF -- requires VTK + Qt6 Qt3D")
endif()
message(STATUS "  OpenGL/GLFW/GLEW/ImGui/BGFX: deprecated from active configuration")
